version: '3'
services:
  api:
    restart: always
    build: .
    ports:
      - 80:8080
    environment:
      MONGO_URI: mongodb://mongo:27017/graphql-db
    volumes:
      - ./:/code
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/lib

volumes:
  mongodb:
